---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggxmean

<!-- badges: start -->
<!-- badges: end -->

The goal of ggxmean is plot the mean of x - and some other things like y! 

## Installation

The development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("EvaMaeRey/ggxmean")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(tidyverse)
library(ggxmean)

## basic example code
cars %>% 
  ggplot() +
  aes(x = speed,
      y = dist) +
  geom_point() + 
  # geom_xvline(alpha = .1,
  #              linetype = "dashed") +
  geom_xmean(color = "firebrick",
             size = 2,
             linetype = "dotted")
```


# another case with faceting

```{r}
mtcars %>% 
  ggplot() + 
  aes(x = wt) + 
  aes(y = mpg) +
  geom_xmean() + # won't appear w/o point, probably as scale is not established
  geom_point() +
  facet_grid(rows = vars(cyl)) #+
  # geom_ymean()
```

# But:

```{r}
palmerpenguins::penguins %>% 
  ggplot() +
  aes(x = bill_length_mm) +
  aes(y = flipper_length_mm) +
  geom_point() +
  # aes(color = species) + 
  geom_xmean() #+
  # geom_ymean() +
  # geom_yhline(alpha = .1) +
  # geom_xvline(alpha = .1) +
  # geom_xdiff() +
  # geom_ydiff() +
  # geom_diffsmultiplied() +
  # aes(x = rank(bill_length_mm)) +
  # aes(y = mean(flipper_length_mm)) +
  # coord_equal()
```


